# Generated by Django 6.0.7 on 2026-07-30 11:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=accounts.models.upload_cv
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.models.upload_profile_picture
            ),
        ),
    ]
