# Generated by Django 6.0.7 on 2026-07-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                max_length=20,
            ),
        ),
    ]
