# Generated by Django 6.0.7 on 2026-08-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_auditlog_details_auditlog_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_email",
            field=models.EmailField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                default="SUCCESS",
                max_length=20,
            ),
        ),
    ]
