# Generated by Django 6.0.7 on 2026-08-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_user_pending_email_alter_auditlog_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("USER", "User"),
                    ("MODERATOR", "Moderator"),
                    ("ADMIN", "Admin"),
                ],
                default="USER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("REGISTER", "Register"),
                    ("VERIFY_EMAIL", "Verify Email"),
                    ("PASSWORD_CHANGE", "Password Change"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("PROFILE_UPDATE", "Profile Update"),
                    ("PROFILE_PICTURE", "Profile Picture Upload"),
                    ("CV_UPLOAD", "CV Upload"),
                    ("EMAIL_CHANGE_REQUEST", "Email Change Request"),
                    ("EMAIL_CHANGED", "Email Changed"),
                    ("ACCOUNT_DELETE", "Account Delete"),
                ],
                max_length=30,
            ),
        ),
    ]
