# Generated by Django 6.0.7 on 2026-08-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_user_role_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("REGISTER", "Register"),
                    ("VERIFY_EMAIL", "Verify Email"),
                    ("PASSWORD_CHANGE", "Password Change"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("PROFILE_UPDATE", "Profile Update"),
                    ("PROFILE_PICTURE", "Profile Picture Upload"),
                    ("CV_UPLOAD", "CV Upload"),
                    ("EMAIL_CHANGE_REQUEST", "Email Change Request"),
                    ("EMAIL_CHANGED", "Email Changed"),
                    ("ACCOUNT_DELETE", "Account Delete"),
                    ("ADMIN_DASHBOARD", "Admin Dashboard"),
                    ("ROLE_CHANGED", "Role Changed"),
                ],
                max_length=30,
            ),
        ),
    ]
