# Generated by Django 6.0.7 on 2026-08-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("REGISTER", "Register"),
                    ("VERIFY_EMAIL", "Verify Email"),
                    ("PASSWORD_CHANGE", "Password Change"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("PROFILE_UPDATE", "Profile Update"),
                    ("PROFILE_PICTURE", "Profile Picture Upload"),
                    ("CV_UPLOAD", "CV Upload"),
                    ("EMAIL_CHANGE_REQUEST", "Email Change Request"),
                    ("EMAIL_CHANGED", "Email Changed"),
                    ("ACCOUNT_DELETE", "Account Delete"),
                    ("ADMIN_DASHBOARD", "Admin Dashboard"),
                    ("ROLE_CHANGED", "Role Changed"),
                    ("VIEW_USERS", "View Users"),
                    ("VIEW_USER", "View Single User"),
                    ("UPDATE_USER_STATUS", "Update User Status"),
                    ("DELETE_USER", "Delete User"),
                ],
                max_length=30,
            ),
        ),
    ]
