# Generated by Django 6.0.7 on 2026-08-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_usersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="device_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
