# Generated by Django 6.0.7 on 2026-08-05 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_usersession_device_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("REGISTER", "Register"),
                    ("VERIFY_EMAIL", "Verify Email"),
                    ("PASSWORD_CHANGE", "Password Change"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("PROFILE_UPDATE", "Profile Update"),
                    ("PROFILE_PICTURE", "Profile Picture Upload"),
                    ("CV_UPLOAD", "CV Upload"),
                    ("EMAIL_CHANGE_REQUEST", "Email Change Request"),
                    ("EMAIL_CHANGED", "Email Changed"),
                    ("LOGOUT", "Logout"),
                    ("LOGOUT_ALL_DEVICES", "Logout all devices"),
                    ("ACCOUNT_DELETE", "Account Delete"),
                    ("ADMIN_DASHBOARD", "Admin Dashboard"),
                    ("ROLE_CHANGED", "Role Changed"),
                    ("VIEW_USERS", "View Users"),
                    ("VIEW_USER", "View Single User"),
                    ("UPDATE_USER_STATUS", "Update User Status"),
                    ("DELETE_USER", "Delete User"),
                    ("RESTORE_USER", "Restore User"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("WELCOME", "Welcome"),
                            ("EMAIL_VERIFIED", "Email Verified"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("ROLE_CHANGED", "Role Changed"),
                            ("ACCOUNT_RESTORED", "Account Restored"),
                            ("ACCOUNT_DELETED", "Account Deleted"),
                            ("SYSTEM", "System"),
                        ],
                        default="SYSTEM",
                        max_length=30,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created"],
            },
        ),
    ]
