# Generated by Django 6.0.7 on 2026-08-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("WELCOME", "Welcome"),
                    ("EMAIL_VERIFIED", "Email Verified"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("ROLE_CHANGED", "Role Changed"),
                    ("ACCOUNT_RESTORED", "Account Restored"),
                    ("ACCOUNT_DELETED", "Account Deleted"),
                    ("SYSTEM", "System"),
                    ("LOGIN", "Login"),
                    ("SECURITY", "Security"),
                ],
                default="SYSTEM",
                max_length=30,
            ),
        ),
    ]
